spring:
  messages:
    baseName: messages
    encoding: UTF-8
    fallbackToSystemLocale: false
  output:
    ansi:
      enabled: always
test:
  rightAnswersCountToPass: 3
  locale: ru-RU
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv
app:
  version: 1.0.0